# Generated by Django 5.2.6 on 2025-09-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_uploadedfile_headers_uploadedfile_row_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMInstructionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_instruction', models.TextField(help_text='Original natural language instruction from user')),
                ('llm_response', models.TextField(help_text='Raw response from LLM')),
                ('parse_error', models.TextField(blank=True, help_text='Error message if parsing failed', null=True)),
                ('column_name', models.CharField(blank=True, help_text='Target column name for modification', max_length=255, null=True)),
                ('regex_pattern', models.TextField(blank=True, help_text='Generated regex pattern', null=True)),
                ('replacement', models.TextField(blank=True, help_text='Replacement value/pattern', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of what the modification does', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score from LLM (0.0 to 1.0)', null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to process instruction in milliseconds', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the instruction was successfully processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(help_text='File that was being processed', on_delete=django.db.models.deletion.CASCADE, related_name='instruction_logs', to='data_processing.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', '-created_at'], name='data_proces_file_id_c5d0d1_idx'), models.Index(fields=['success', '-created_at'], name='data_proces_success_20e8ef_idx')],
            },
        ),
    ]
