# Generated by Django 5.2.6 on 2025-09-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_llminstructionlog'),
    ]

    operations = [
    ]
